allowBuilds:
  electron-winstaller: set this to true or false
  uiohook-napi: set this to true or false
overrides:
  global-agent: 4.1.3
  http-cache-semantics: 4.3.0
  shell-quote: 1.12.0
  source-map-js: 1.2.2
